#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr  5 22:11:58 2020

@author: mawais
"""

def compound_interest(principle,rate,time):
    
    CI = principle * (pow(1 + rate / 100, time))
    print("Compound interest is" , CI)
    
compound_interest(10000, 10.25, 5)