#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr  3 20:22:17 2020

@author: mawais
"""
#import modules
import socket
import subprocess
import sys
from datetime import datetime
#clear the screen
subprocess.call('clear', shell = True)
#Ask for input for remote server
remoteServer = input("Enter a remote host to scan: ")
remoteServerIP = socket.gethostbyname(remoteServer)

#Print information on which host we are about to scan
print ("-" * 60)
print("Please wait, scanning remote host", remoteServerIP)
print ("-" * 60)

#check the timing of the scan
time1 = datetime.now()

#using the range function to specify ports & also include error handling for catching errors
try:
    for port in range(1,1025):
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        result = sock.connect_ex((remoteServerIP, port))
        if result ==0:
            print"Port{}:   Open".format(port)
        sock.close()
        
except KeyboardInterrupt:
   print "You pressed Ctrl+C"
   sys.exit()
   
except socket.gaierror:
    print 'Hostname could not be resolved.Exiting'
    sys.exit()
    
except socket.error:
    print"Couldn't connect to server"
    sys.exit()
    
#check the time one more tome
time2 = datetime.now()

#calculate the change in time, to see how long it would take for the script to run
totaltime = time2-time1

#print the information to the screen
print 'Scanning Completed in: ', total
    
